### ISSUE TITLE
Ejercicio 2-Un sensor de temperatura, que tiene un rango de medida de 20-250 °C, entrega una lectura de 55 °C.

### ISSUE THREAD

**Issue by GiseRomero** [ISPC-TST-Sensores-y-Actuadores/practica-de-la-2da-semana-grupo-4#4]
Un sensor de temperatura, que tiene un rango de medida de 20-250 °C, entrega una lectura de 55 °C. Especificar el error en la lectura si la exactitud se expresa de las siguientes formas, indicando el rango de medición en cada caso.

**Comment by FedeBirge** [comment]
subido
